version: "3"

services:
  php74:
    image: php:7.4-apache
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
    restart: always

  php80:
    image: php:8.0-apache
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    restart: always

  composer:
    image: composer
    volumes:
      - ./:/app
    command: install
    restart: "no"
